// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: BUSL-1.1

syntax = "proto3";

package kacho.cloud.compute.v1;

import "google/api/annotations.proto";
import "kacho/cloud/api/operation.proto";
import "kacho/cloud/maintenance/v2/common.proto";
import "kacho/cloud/operation/operation.proto";
import "kacho/iam/authz/v1/authz_options.proto";

option go_package = "github.com/PRO-Robotech/kacho-proto/gen/go/kacho/cloud/compute/v1;computev1";

// A set of methods for managing maintenances in a service.
service MaintenanceService {
  // Lists maintenances by conditions, specified in request.
  rpc List(kacho.cloud.maintenance.v2.ListMaintenancesRequest) returns (kacho.cloud.maintenance.v2.ListMaintenancesResponse) {
    option (google.api.http) = {get: "/compute/v1/maintenances"};
    option (kacho.iam.authz.v1.permission)        = "compute.maintenanceses.list";
    option (kacho.iam.authz.v1.required_relation) = "viewer";
    option (kacho.iam.authz.v1.scope_extractor)   = {
      object_type:        "project"
      from_request_field: "*"
    };
    option (kacho.iam.authz.v1.required_acr_min)  = "2";
  }

  // Retrieves the specific Maintenance by ID.
  rpc Get(kacho.cloud.maintenance.v2.GetMaintenanceRequest) returns (kacho.cloud.maintenance.v2.Maintenance) {
    option (google.api.http) = {get: "/compute/v1/maintenances/{maintenance_id}"};
    option (kacho.iam.authz.v1.permission)        = "compute.maintenances.get";
    option (kacho.iam.authz.v1.required_relation) = "viewer";
    option (kacho.iam.authz.v1.scope_extractor)   = {
      object_type:        "project"
      from_request_field: "*"
    };
    option (kacho.iam.authz.v1.required_acr_min)  = "2";
  }

  // Allows user to reschedule Maintenance to another date and time.
  rpc Reschedule(kacho.cloud.maintenance.v2.RescheduleMaintenanceRequest) returns (operation.Operation) {
    option (google.api.http) = {post: "/compute/v1/maintenances/{maintenance_id}:reschedule" body: "*"};
    option (kacho.cloud.api.operation) = {
      response: "kacho.cloud.maintenance.v2.Maintenance"
    };
    option (kacho.iam.authz.v1.permission)        = "compute.reschedule_maintenances.reschedule";
    option (kacho.iam.authz.v1.required_relation) = "editor";
    option (kacho.iam.authz.v1.scope_extractor)   = {
      object_type:        "project"
      from_request_field: "*"
    };
    option (kacho.iam.authz.v1.required_acr_min)  = "2";
  }
}
